name: build
on:
  push:
    branches:
      - main
jobs:
  minimal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .
          submodules: 'recursive'
      - uses: nixbuild/nix-quick-install-action@v29
      - run: nix develop --command make
